import { QueryAnswerResponse } from "@/lib/types";

export const DEMO_QUERY =
  "I currently take cetirizine for my pollen allergy. can i take both ibuprofen and aspirin against swollen eyes?";

const generatedAt = "2026-06-11T00:00:00Z";

export const demoQueryAnswer: QueryAnswerResponse = {
  understanding: {
    query: DEMO_QUERY,
    extraction_mode: "hybrid",
    state: {
      primary_drug: "ibuprofen",
      all_drugs_mentioned: ["cetirizine", "ibuprofen", "aspirin"],
      current_medications: ["cetirizine"],
      allergies: ["pollen allergy"],
      conditions: ["swollen eyes"],
      patient_context: [],
      intent: "interaction_check",
      intents: ["interaction_check", "medication_use", "symptom_context"],
    },
    resolved_drugs: [
      {
        text: "ibuprofen",
        role: "primary_drug",
        selected_concept: {
          rxcui: "5640",
          name: "ibuprofen",
          tty: "IN",
          sab: "RXNORM",
        },
        candidates: [
          {
            concept: {
              rxcui: "5640",
              name: "ibuprofen",
              tty: "IN",
              sab: "RXNORM",
            },
            match_type: "fixture",
            score: 1,
          },
        ],
      },
      {
        text: "cetirizine",
        role: "current_medication",
        selected_concept: {
          rxcui: "20610",
          name: "cetirizine",
          tty: "IN",
          sab: "RXNORM",
        },
        candidates: [
          {
            concept: {
              rxcui: "20610",
              name: "cetirizine",
              tty: "IN",
              sab: "RXNORM",
            },
            match_type: "fixture",
            score: 1,
          },
        ],
      },
      {
        text: "aspirin",
        role: "mentioned_drug",
        selected_concept: {
          rxcui: "1191",
          name: "aspirin",
          tty: "IN",
          sab: "RXNORM",
        },
        candidates: [
          {
            concept: {
              rxcui: "1191",
              name: "aspirin",
              tty: "IN",
              sab: "RXNORM",
            },
            match_type: "fixture",
            score: 1,
          },
        ],
      },
    ],
    primary_dossier: {
      query: "ibuprofen",
      generated_at: generatedAt,
      resolved_drug: {
        rxcui: "5640",
        name: "ibuprofen",
        tty: "IN",
        sab: "RXNORM",
      },
      resolution_candidates: [
        {
          concept: {
            rxcui: "5640",
            name: "ibuprofen",
            tty: "IN",
            sab: "RXNORM",
          },
          match_type: "fixture",
          score: 1,
        },
      ],
      rxnorm_neighborhood: {
        depth: 2,
        truncated: false,
        nodes: [
          { rxcui: "5640", name: "ibuprofen", tty: "IN", sab: "RXNORM" },
          {
            rxcui: "197805",
            name: "ibuprofen 200 MG Oral Tablet",
            tty: "SCD",
            sab: "RXNORM",
          },
          {
            rxcui: "310964",
            name: "ibuprofen Oral Product",
            tty: "SCDG",
            sab: "RXNORM",
          },
          { rxcui: "1191", name: "aspirin", tty: "IN", sab: "RXNORM" },
          {
            rxcui: "20610",
            name: "cetirizine",
            tty: "IN",
            sab: "RXNORM",
          },
        ],
        edges: [
          {
            source_rxcui: "197805",
            source_name: "ibuprofen 200 MG Oral Tablet",
            source_tty: "SCD",
            target_rxcui: "5640",
            target_name: "ibuprofen",
            target_tty: "IN",
            relation: "has_ingredient",
            source: "RXNORM",
          },
          {
            source_rxcui: "310964",
            source_name: "ibuprofen Oral Product",
            source_tty: "SCDG",
            target_rxcui: "5640",
            target_name: "ibuprofen",
            target_tty: "IN",
            relation: "has_ingredient",
            source: "RXNORM",
          },
          {
            source_rxcui: "1191",
            source_name: "aspirin",
            source_tty: "IN",
            target_rxcui: "5640",
            target_name: "ibuprofen",
            target_tty: "IN",
            relation: "fixture_context",
            source: "RXNORM",
          },
        ],
      },
      label_evidence: {
        rxcui: "5640",
        labels_found: 3,
        label_limit: 10,
        retrieval_mode: "fixture",
        label_records: [
          {
            source_id: "fixture-ibuprofen-1",
            id: "fixture-ibuprofen-spl-1",
            set_id: "fixture-ibuprofen-set-1",
            spl_ids: ["fixture-ibuprofen-spl-1"],
            spl_set_ids: ["fixture-ibuprofen-set-1"],
            effective_time: "20260101",
            version: "demo",
            brand_names: ["Advil"],
            generic_names: ["Ibuprofen"],
            manufacturer_names: ["Demo Label Manufacturer"],
            product_ndcs: ["0000-0001"],
            product_types: ["HUMAN OTC DRUG"],
            routes: ["ORAL"],
            substance_names: ["IBUPROFEN"],
            rxcuis: ["5640"],
            provenance_tags: ["medication_specific"],
          },
          {
            source_id: "fixture-ibuprofen-2",
            id: "fixture-ibuprofen-spl-2",
            set_id: "fixture-ibuprofen-set-2",
            spl_ids: ["fixture-ibuprofen-spl-2"],
            spl_set_ids: ["fixture-ibuprofen-set-2"],
            effective_time: "20260101",
            version: "demo",
            brand_names: ["Motrin"],
            generic_names: ["Ibuprofen"],
            manufacturer_names: ["Demo Consumer Health"],
            product_ndcs: ["0000-0002"],
            product_types: ["HUMAN OTC DRUG"],
            routes: ["ORAL"],
            substance_names: ["IBUPROFEN"],
            rxcuis: ["5640"],
            provenance_tags: ["medication_specific"],
          },
        ],
        summary_metadata: {
          brand_names: ["Advil", "Motrin"],
          generic_names: ["Ibuprofen"],
          manufacturer_names: ["Demo Label Manufacturer", "Demo Consumer Health"],
        },
        sections: {
          warnings: [
            {
              section: "warnings",
              source_id: "fixture-ibuprofen-1",
              source: "openfda_fixture",
              effective_time: "20260101",
              provenance_tags: ["medication_specific"],
              text: "Demo label excerpt: ibuprofen labels can include warnings about stomach bleeding risk, allergy alerts, and asking a health professional before use with other pain relievers.",
            },
          ],
          drug_interactions: [
            {
              section: "drug_interactions",
              source_id: "fixture-ibuprofen-1",
              source: "openfda_fixture",
              effective_time: "20260101",
              provenance_tags: ["interaction_specific"],
              text: "Demo label excerpt: ask a doctor or pharmacist before use if taking aspirin for heart attack or stroke, because ibuprofen may decrease this benefit of aspirin.",
            },
          ],
          indications_and_usage: [
            {
              section: "indications_and_usage",
              source_id: "fixture-ibuprofen-2",
              source: "openfda_fixture",
              effective_time: "20260101",
              provenance_tags: ["medication_specific"],
              text: "Demo label excerpt: ibuprofen is used as a pain reliever and fever reducer.",
            },
          ],
        },
        section_flags: {
          warnings: true,
          drug_interactions: true,
          indications_and_usage: true,
        },
        errors: [],
      },
      notes: ["Demo fixture dossier. No live API calls were made."],
    },
    warnings: ["Demo fixture loaded; no LLM or live API calls were made."],
    errors: [],
  },
  answer: {
    summary:
      "This demo response is loaded from a local fixture. It shows how rx-ray would ground a question about cetirizine, ibuprofen, aspirin, pollen allergy, and swollen eyes in retrieved label-style evidence without making a live LLM request.",
    bullets: [
      {
        text: "The fixture includes ibuprofen label evidence that explicitly mentions aspirin in a drug-interaction-style section.",
        citations: [
          {
            source_id: "fixture-ibuprofen-1",
            section: "drug_interactions",
            snippet:
              "ask a doctor or pharmacist before use if taking aspirin...",
          },
        ],
      },
      {
        text: "The fixture includes separate medication-specific label evidence for aspirin and cetirizine so the multi-drug tabs and evidence map can be tested.",
        citations: [
          {
            source_id: "fixture-aspirin-1",
            section: "warnings",
            snippet: "aspirin labels can include allergy alerts...",
          },
          {
            source_id: "fixture-cetirizine-1",
            section: "warnings",
            snippet: "cetirizine labels can include drowsiness warnings...",
          },
        ],
      },
    ],
    limitations: [
      "This is static demo data, not a fresh FDA label lookup.",
      "The fixture is intentionally compact and may not represent the full public label record set.",
      "The response is for UI testing only and is not medical advice.",
    ],
    safety_note:
      "This educational prototype summarizes public-label-style evidence and does not provide medical advice.",
  },
  secondary_evidence: [
    {
      mention_text: "cetirizine",
      role: "current_medication",
      resolved_concept: {
        rxcui: "20610",
        name: "cetirizine",
        tty: "IN",
        sab: "RXNORM",
      },
      retrieval_modes: ["fixture"],
      rxnorm_context: {
        primary_rxcui: "5640",
        secondary_rxcui: "20610",
        status: "no_direct_relationship",
        summary:
          "Demo RxNorm terminology context: no direct terminology relationship is shown between ibuprofen and cetirizine.",
        direct_edges: [],
        shared_neighbors: [],
      },
      label_evidence: {
        rxcui: "20610",
        labels_found: 1,
        label_limit: 3,
        retrieval_mode: "fixture",
        label_records: [
          {
            source_id: "fixture-cetirizine-1",
            id: "fixture-cetirizine-spl-1",
            set_id: "fixture-cetirizine-set-1",
            spl_ids: ["fixture-cetirizine-spl-1"],
            spl_set_ids: ["fixture-cetirizine-set-1"],
            effective_time: "20260101",
            version: "demo",
            brand_names: ["Zyrtec"],
            generic_names: ["Cetirizine"],
            manufacturer_names: ["Demo Allergy Health"],
            product_ndcs: ["0000-0003"],
            product_types: ["HUMAN OTC DRUG"],
            routes: ["ORAL"],
            substance_names: ["CETIRIZINE"],
            rxcuis: ["20610"],
            provenance_tags: ["medication_specific"],
          },
        ],
        summary_metadata: {
          brand_names: ["Zyrtec"],
          generic_names: ["Cetirizine"],
          manufacturer_names: ["Demo Allergy Health"],
        },
        sections: {
          warnings: [
            {
              section: "warnings",
              source_id: "fixture-cetirizine-1",
              source: "openfda_fixture",
              effective_time: "20260101",
              provenance_tags: ["medication_specific"],
              text: "Demo label excerpt: cetirizine labels can include drowsiness warnings and advice to ask a doctor before use in some situations.",
            },
          ],
          indications_and_usage: [
            {
              section: "indications_and_usage",
              source_id: "fixture-cetirizine-1",
              source: "openfda_fixture",
              effective_time: "20260101",
              provenance_tags: ["medication_specific"],
              text: "Demo label excerpt: cetirizine is used for allergy symptoms.",
            },
          ],
        },
        section_flags: {
          warnings: true,
          indications_and_usage: true,
        },
        errors: [],
      },
      interaction_label_evidence: null,
    },
    {
      mention_text: "aspirin",
      role: "mentioned_drug",
      resolved_concept: {
        rxcui: "1191",
        name: "aspirin",
        tty: "IN",
        sab: "RXNORM",
      },
      retrieval_modes: ["fixture", "interaction_targeted_lookup"],
      rxnorm_context: {
        primary_rxcui: "5640",
        secondary_rxcui: "1191",
        status: "shared_terminology_context",
        summary:
          "Demo RxNorm terminology context: aspirin and ibuprofen are both represented as ingredient concepts, but this is terminology context, not clinical interaction evidence.",
        direct_edges: [],
        shared_neighbors: [
          {
            rxcui: "analgesic-demo",
            name: "analgesic terminology context",
            tty: "DFG",
            sab: "RXNORM",
          },
        ],
      },
      label_evidence: {
        rxcui: "1191",
        labels_found: 2,
        label_limit: 3,
        retrieval_mode: "fixture",
        label_records: [
          {
            source_id: "fixture-aspirin-1",
            id: "fixture-aspirin-spl-1",
            set_id: "fixture-aspirin-set-1",
            spl_ids: ["fixture-aspirin-spl-1"],
            spl_set_ids: ["fixture-aspirin-set-1"],
            effective_time: "20260101",
            version: "demo",
            brand_names: ["Bayer Aspirin"],
            generic_names: ["Aspirin"],
            manufacturer_names: ["Demo Aspirin Manufacturer"],
            product_ndcs: ["0000-0004"],
            product_types: ["HUMAN OTC DRUG"],
            routes: ["ORAL"],
            substance_names: ["ASPIRIN"],
            rxcuis: ["1191"],
            provenance_tags: ["medication_specific"],
          },
          {
            source_id: "fixture-aspirin-interaction-1",
            id: "fixture-aspirin-spl-2",
            set_id: "fixture-aspirin-set-2",
            spl_ids: ["fixture-aspirin-spl-2"],
            spl_set_ids: ["fixture-aspirin-set-2"],
            effective_time: "20260101",
            version: "demo",
            brand_names: ["Aspirin Demo Label"],
            generic_names: ["Aspirin"],
            manufacturer_names: ["Demo Interaction Labeler"],
            product_ndcs: ["0000-0005"],
            product_types: ["HUMAN OTC DRUG"],
            routes: ["ORAL"],
            substance_names: ["ASPIRIN"],
            rxcuis: ["1191"],
            provenance_tags: ["interaction_specific"],
          },
        ],
        summary_metadata: {
          brand_names: ["Bayer Aspirin", "Aspirin Demo Label"],
          generic_names: ["Aspirin"],
          manufacturer_names: [
            "Demo Aspirin Manufacturer",
            "Demo Interaction Labeler",
          ],
        },
        sections: {
          warnings: [
            {
              section: "warnings",
              source_id: "fixture-aspirin-1",
              source: "openfda_fixture",
              effective_time: "20260101",
              provenance_tags: ["medication_specific"],
              text: "Demo label excerpt: aspirin labels can include allergy alerts, bleeding warnings, and advice to ask a doctor before use with other medicines.",
            },
          ],
          drug_interactions: [
            {
              section: "drug_interactions",
              source_id: "fixture-aspirin-interaction-1",
              source: "openfda_fixture",
              effective_time: "20260101",
              provenance_tags: ["interaction_specific"],
              text: "Demo label excerpt: aspirin interaction-targeted label text mentions ibuprofen as a medicine that may require professional guidance.",
            },
          ],
        },
        section_flags: {
          warnings: true,
          drug_interactions: true,
        },
        errors: [],
      },
      interaction_label_evidence: null,
    },
  ],
  question_evidence_map: {
    nodes: [
      {
        id: "question",
        kind: "question",
        label: "Question",
        subtitle: DEMO_QUERY,
        tags: ["fixture"],
      },
      {
        id: "concept-ibuprofen",
        kind: "query_concept",
        label: "ibuprofen",
        role: "primary_drug",
        tags: ["fixture"],
      },
      {
        id: "concept-cetirizine",
        kind: "query_concept",
        label: "cetirizine",
        role: "current_medication",
        tags: ["fixture"],
      },
      {
        id: "concept-aspirin",
        kind: "query_concept",
        label: "aspirin",
        role: "mentioned_drug",
        tags: ["fixture"],
      },
      {
        id: "concept-pollen-allergy",
        kind: "query_concept",
        label: "pollen allergy",
        role: "condition",
        tags: ["fixture"],
      },
      {
        id: "rx-ibuprofen",
        kind: "resolved_medication",
        label: "ibuprofen",
        role: "primary_drug",
        rxcui: "5640",
        tags: ["fixture"],
      },
      {
        id: "rx-cetirizine",
        kind: "resolved_medication",
        label: "cetirizine",
        role: "current_medication",
        rxcui: "20610",
        tags: ["fixture"],
      },
      {
        id: "rx-aspirin",
        kind: "resolved_medication",
        label: "aspirin",
        role: "mentioned_drug",
        rxcui: "1191",
        tags: ["fixture"],
      },
      {
        id: "source-ibuprofen-1",
        kind: "label_source",
        label: "Advil",
        subtitle: "Demo Label Manufacturer",
        rxcui: "5640",
        source_id: "fixture-ibuprofen-1",
        evidence_scope: "primary",
        tags: ["medication_specific", "interaction_specific"],
      },
      {
        id: "source-cetirizine-1",
        kind: "label_source",
        label: "Zyrtec",
        subtitle: "Demo Allergy Health",
        rxcui: "20610",
        source_id: "fixture-cetirizine-1",
        evidence_scope: "secondary",
        tags: ["medication_specific"],
      },
      {
        id: "source-aspirin-1",
        kind: "label_source",
        label: "Bayer Aspirin",
        subtitle: "Demo Aspirin Manufacturer",
        rxcui: "1191",
        source_id: "fixture-aspirin-1",
        evidence_scope: "secondary",
        tags: ["medication_specific"],
      },
      {
        id: "source-aspirin-interaction-1",
        kind: "label_source",
        label: "Aspirin Demo Label",
        subtitle: "Demo Interaction Labeler",
        rxcui: "1191",
        source_id: "fixture-aspirin-interaction-1",
        evidence_scope: "secondary",
        tags: ["interaction_targeted_lookup"],
      },
      {
        id: "section-ibuprofen-interactions",
        kind: "label_section",
        label: "Drug Interactions",
        rxcui: "5640",
        source_id: "fixture-ibuprofen-1",
        section: "drug_interactions",
        evidence_scope: "primary",
        tags: ["interaction_specific"],
      },
      {
        id: "section-aspirin-warnings",
        kind: "label_section",
        label: "Warnings",
        rxcui: "1191",
        source_id: "fixture-aspirin-1",
        section: "warnings",
        evidence_scope: "secondary",
        tags: ["medication_specific"],
      },
      {
        id: "section-cetirizine-warnings",
        kind: "label_section",
        label: "Warnings",
        rxcui: "20610",
        source_id: "fixture-cetirizine-1",
        section: "warnings",
        evidence_scope: "secondary",
        tags: ["medication_specific"],
      },
      {
        id: "rx-context-aspirin",
        kind: "rxnorm_context",
        label: "Terminology context",
        subtitle:
          "Aspirin and ibuprofen are both ingredient concepts in this demo context.",
        rxcui: "1191",
        tags: ["fixture"],
      },
    ],
    edges: [
      {
        id: "question-concept-ibuprofen",
        source: "question",
        target: "concept-ibuprofen",
        kind: "has_role",
        label: "extracted as",
        tags: ["fixture"],
      },
      {
        id: "question-concept-cetirizine",
        source: "question",
        target: "concept-cetirizine",
        kind: "has_role",
        label: "extracted as",
        tags: ["fixture"],
      },
      {
        id: "question-concept-aspirin",
        source: "question",
        target: "concept-aspirin",
        kind: "has_role",
        label: "extracted as",
        tags: ["fixture"],
      },
      {
        id: "question-concept-pollen",
        source: "question",
        target: "concept-pollen-allergy",
        kind: "has_role",
        label: "extracted as",
        tags: ["fixture"],
      },
      {
        id: "concept-ibuprofen-resolved",
        source: "concept-ibuprofen",
        target: "rx-ibuprofen",
        kind: "resolved_as",
        label: "resolved as",
        rxcui: "5640",
        tags: ["fixture"],
      },
      {
        id: "concept-cetirizine-resolved",
        source: "concept-cetirizine",
        target: "rx-cetirizine",
        kind: "resolved_as",
        label: "resolved as",
        rxcui: "20610",
        tags: ["fixture"],
      },
      {
        id: "concept-aspirin-resolved",
        source: "concept-aspirin",
        target: "rx-aspirin",
        kind: "resolved_as",
        label: "resolved as",
        rxcui: "1191",
        tags: ["fixture"],
      },
      {
        id: "ibuprofen-source",
        source: "rx-ibuprofen",
        target: "source-ibuprofen-1",
        kind: "has_label_source",
        label: "label source",
        source_id: "fixture-ibuprofen-1",
        tags: ["fixture"],
      },
      {
        id: "cetirizine-source",
        source: "rx-cetirizine",
        target: "source-cetirizine-1",
        kind: "has_label_source",
        label: "label source",
        source_id: "fixture-cetirizine-1",
        tags: ["fixture"],
      },
      {
        id: "aspirin-source",
        source: "rx-aspirin",
        target: "source-aspirin-1",
        kind: "has_label_source",
        label: "label source",
        source_id: "fixture-aspirin-1",
        tags: ["fixture"],
      },
      {
        id: "aspirin-interaction-source",
        source: "rx-aspirin",
        target: "source-aspirin-interaction-1",
        kind: "interaction_lookup_source",
        label: "interaction-specific lookup source",
        source_id: "fixture-aspirin-interaction-1",
        tags: ["interaction_targeted_lookup"],
      },
      {
        id: "ibuprofen-section",
        source: "source-ibuprofen-1",
        target: "section-ibuprofen-interactions",
        kind: "has_label_section",
        label: "label section",
        source_id: "fixture-ibuprofen-1",
        section: "drug_interactions",
        tags: ["fixture"],
      },
      {
        id: "aspirin-section",
        source: "source-aspirin-1",
        target: "section-aspirin-warnings",
        kind: "has_label_section",
        label: "label section",
        source_id: "fixture-aspirin-1",
        section: "warnings",
        tags: ["fixture"],
      },
      {
        id: "cetirizine-section",
        source: "source-cetirizine-1",
        target: "section-cetirizine-warnings",
        kind: "has_label_section",
        label: "label section",
        source_id: "fixture-cetirizine-1",
        section: "warnings",
        tags: ["fixture"],
      },
      {
        id: "aspirin-rx-context",
        source: "rx-ibuprofen",
        target: "rx-context-aspirin",
        kind: "has_terminology_context",
        label: "terminology context",
        tags: ["fixture"],
      },
      {
        id: "aspirin-rx-context-target",
        source: "rx-aspirin",
        target: "rx-context-aspirin",
        kind: "has_terminology_context",
        label: "terminology context",
        tags: ["fixture"],
      },
    ],
    summary_counts: {
      question: 1,
      query_concept: 4,
      resolved_medication: 3,
      label_source: 4,
      label_section: 3,
      rxnorm_context: 1,
    },
  },
  coverage: {
    items: [
      {
        category: "primary_drug",
        label: "ibuprofen",
        status: "addressed",
        reason: "Demo primary medication evidence is available.",
        matched_evidence: "ibuprofen label evidence",
        source_id: "fixture-ibuprofen-1",
        section: "drug_interactions",
        target_rxcui: "5640",
      },
      {
        category: "mentioned_medication",
        label: "aspirin",
        status: "addressed",
        reason: "Demo secondary medication evidence is available.",
        matched_evidence: "aspirin label evidence",
        source_id: "fixture-aspirin-1",
        section: "warnings",
        target_rxcui: "1191",
      },
      {
        category: "current_medication",
        label: "cetirizine",
        status: "addressed",
        reason: "Demo current-medication evidence is available.",
        matched_evidence: "cetirizine label evidence",
        source_id: "fixture-cetirizine-1",
        section: "warnings",
        target_rxcui: "20610",
      },
      {
        category: "condition",
        label: "swollen eyes",
        status: "not_found_in_evidence",
        reason:
          "The demo fixture does not include label text specifically addressing swollen eyes.",
      },
      {
        category: "condition",
        label: "pollen allergy",
        status: "not_found_in_evidence",
        reason:
          "The demo fixture includes allergy-medication context but not patient-specific pollen allergy guidance.",
      },
    ],
    summary_counts: {
      addressed: 3,
      not_found_in_evidence: 2,
    },
  },
  warnings: ["Demo fixture loaded; no LLM or live API calls were made."],
  errors: [],
};
